# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRGAccount' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRGAccount

  pod 'RTRootNavigationController'
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

  pod 'HRGVendor', :path => '../HRGVendor'
  pod 'HRGTool', :path => '../HRGTool'
  pod 'HRGModel', :path => '../HRGModel'
  pod 'HRGCustomView', :path => '../HRGCustomView'
  pod 'HRGDataLayer', :path => '../HRGDataLayer'

end
