# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRGIOM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRGIOM
  
#  pod 'AMapNavi'#导航SDK,已包含3D地图，无需单独引入3D地图
#  pod 'AMapSearch'#地图SDK搜索功能
  pod 'AMapLocation'#定位SDK
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

  pod 'HRGVendor', :path => '../HRGVendor'
  pod 'HRGTool', :path => '../HRGTool'
  pod 'HRGModel', :path => '../HRGModel'
  pod 'HRGCustomView', :path => '../HRGCustomView'
  pod 'HRGDataLayer', :path => '../HRGDataLayer'
  pod 'HRGAccount', :path => '../HRGAccount'
  pod 'HRGAccountCatogery', :path => '../HRGAccountCatogery'

end
