# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRGDataLayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRGDataLayer

  pod 'AMapLocation'#定位SDK
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
  
  pod 'YYKit'
  pod 'AFNetworking'
  
  pod 'HRGModel', :path => '../HRGModel'

end
