# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRGCustomView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRGCustomView

  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MBProgressHUD'

end
